
############################# Build ##############################

noJSConfigInAssets = false
useResourceCacheWhen = 'fallback'
[buildStats]
enable = true
[[cachebusters]]
source = 'assets/watching/hugo_stats\.json'
target = 'style\.css'
[[cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
[[cachebusters]]
source = 'assets/.*\.(js|ts|jsx|tsx)'
target = 'js'
[[cachebusters]]
source = 'assets/.*\.(css|scss|sass)'
target = 'css'
[[cachebusters]]
source = 'data/.*\.(.*)$'
target = 'css'
[[cachebusters]]
source = 'assets/.*\.(.*)$'
target = '$1'
