baseURL = "https://orbiting.com/"
languageCode = "en-us"
title = "Orbiting - visual messages"

publishDir = "public"

disableKinds = ["taxonomy", "taxonomyTerm", "category", "RSS", "section"]


[params]

[Permalinks]
page = "/:filename/"
