[build]
base = "packages/chat"
command = "npm install && npx expo export --platform web"
publish = "dist"

[context.production.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"

[context.deploy-preview]
command = "npm install && npx expo export --platform web"

[context.deploy-preview.environment]
NODE_VERSION = "20"
NPM_VERSION = "10"
