
[context.production.environment]
HUGO_VERSION = "0.140.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.23"         # Add this line to specify a modern Go version

[build]
HUGO_VERSION = "0.140.0"
command = "cd packages/hugo; hugo --gc --minify"
publish = "packages/hugo/public"
